TEMPLATEROOT = ..

# compilation flags for gdb

CFLAGS  = -O1 -g
ASFLAGS = -g 

# object files

OBJS=  $(STARTUP) 	main.o\
			f3d_rtc.o\
			f3d_systick.o \
			queue.o \
			f3d_user_btn.o \
			f3d_led.o \
			f3d_uart.o \
			f3d_gyro.o \
			f3d_delay.o \
			f3d_lcd_sd.o \
			glcdfont.o \
			stm32f30x_rcc.o \
			stm32f30x_tim.o \
			stm32f30x_gpio.o \
			stm32f30x_usart.o \
			stm32f30x_spi.o \
			stm32f30x_i2c.o\
			stm32f30x_rtc.o\
			stm32f30x_misc.o\
			stm32f30x_pwr.o\
			newlib_stubs.o

# include common make file

include $(TEMPLATEROOT)/c335.mk


