#This is the Makefile for lab04
#* Author: Jarod England username:jkenglan and Steven Russell
#* Date Created: 9/23/16
#* Last Modified by: Jarod England
#* Date Last Modified: 9/23/16
#* Assignment: lab04
#* Part of: lab04

TEMPLATEROOT = ..

# compilation flags for gdb

CFLAGS  = -O1 -g
ASFLAGS = -g 

# object files

OBJS=  $(STARTUP) main.o f3d_led.o f3d_uart.o stm32f30x_rcc.o stm32f30x_gpio.o stm32f30x_usart.o newlib_stubs.o

# include common make file

include $(TEMPLATEROOT)/c335.mk


