#This is the Makefile. This makes the file for the program. 
#//Author: Jarod England
#// Date Created: Sept. 2016  
#// Last Modified by: Jarod England   
#// Date Last Modified: Oct 5. 2016    
#// Assignment: Lab5
#// Part of: lab5 



TEMPLATEROOT = ..

# compilation flags for gdb

CFLAGS  = -O1 -g
ASFLAGS = -g 

# object files

OBJS=  $(STARTUP) main.o f3d_gyro.o f3d_led.o f3d_uart.o f3d_user_btn.o stm32f30x_spi.o stm32f30x_rcc.o stm32f30x_gpio.o stm32f30x_usart.o newlib_stubs.o 

# include common make file

include $(TEMPLATEROOT)/c335.mk


