#This is the Makefile for the program for lab03
#* Author: Jarod England username:jkenglan and Minyang Tie username:minytie
#* Date Created: 9/12/16
#* Last Modified by: Jarod England
#* Date Last Modified: 9/12/16
#* Assignment: C on Discovery
#* Part of: lab03



TEMPLATEROOT = ..

# compilation flags for gdb

CFLAGS  = -O1 -g
ASFLAGS = -g 

# object files

OBJS=  $(STARTUP) main.o f3d_led.o f3d_user_btn.o stm32f30x_rcc.o stm32f30x_gpio.o

# include common make file

include $(TEMPLATEROOT)/c335.mk


